title: 'A Spring Boot Application using Spring Data JPA'
author: Shawn Sherwood
description: >
  a developer journal to building a (somewhat) realistic application using Spring Boot and
  Spring Data JPA.
theme: jekyll-theme-tactile
baseurl: "spring-boot-jpa"
url: "undertree.io"
permalink: /:title